# render.yaml
services:
  - type: web
    name: football-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.run:app
    branch: master
    autoDeploy: true
